/*
 * Decompiled with CFR 0.148.
 * 
 * Could not load the following classes:
 *  net.minecraft.item.Item
 */
package lotr.common.entity.npc;

import lotr.common.LOTRMod;
import lotr.common.entity.animal.LOTREntityCamel;
import lotr.common.entity.animal.LOTREntityElk;
import lotr.common.entity.animal.LOTREntityHorse;
import lotr.common.entity.animal.LOTREntityRam;
import lotr.common.entity.animal.LOTREntityRhino;
import lotr.common.entity.animal.LOTREntityShirePony;
import lotr.common.entity.animal.LOTREntityWildBoar;
import lotr.common.entity.animal.LOTREntityZebra;
import lotr.common.entity.npc.LOTREntityAngbandBalrog;
import lotr.common.entity.npc.LOTREntityAngbandBerserk;
import lotr.common.entity.npc.LOTREntityAngbandCrossbow;
import lotr.common.entity.npc.LOTREntityAngbandElf;
import lotr.common.entity.npc.LOTREntityAngbandOrc;
import lotr.common.entity.npc.LOTREntityAngbandOrcArcher;
import lotr.common.entity.npc.LOTREntityAngbandOrcZnam;
import lotr.common.entity.npc.LOTREntityAngbandRuinsWraith;
import lotr.common.entity.npc.LOTREntityAngbandSpiderFire;
import lotr.common.entity.npc.LOTREntityAngbandSpiderIce;
import lotr.common.entity.npc.LOTREntityAngbandSpiderObsidian;
import lotr.common.entity.npc.LOTREntityAngbandTrollFire;
import lotr.common.entity.npc.LOTREntityAngbandTrollObsidian;
import lotr.common.entity.npc.LOTREntityAngbandUruc;
import lotr.common.entity.npc.LOTREntityAngbandWarg;
import lotr.common.entity.npc.LOTREntityAngbandWargBombardier;
import lotr.common.entity.npc.LOTREntityAngbandWargFire;
import lotr.common.entity.npc.LOTREntityAngbandWargIce;
import lotr.common.entity.npc.LOTREntityAngbandWargObsidian;
import lotr.common.entity.npc.LOTREntityAngbandZnam;
import lotr.common.entity.npc.LOTREntityAngbandZnam1;
import lotr.common.entity.npc.LOTREntityAngbandZnam2;
import lotr.common.entity.npc.LOTREntityAngmarBannerBearer;
import lotr.common.entity.npc.LOTREntityAngmarHillman;
import lotr.common.entity.npc.LOTREntityAngmarHillmanAxeThrower;
import lotr.common.entity.npc.LOTREntityAngmarHillmanBannerBearer;
import lotr.common.entity.npc.LOTREntityAngmarHillmanWarrior;
import lotr.common.entity.npc.LOTREntityAngmarOrc;
import lotr.common.entity.npc.LOTREntityAngmarOrcArcher;
import lotr.common.entity.npc.LOTREntityAngmarOrcBombardier;
import lotr.common.entity.npc.LOTREntityAngmarWarg;
import lotr.common.entity.npc.LOTREntityAngmarWargBombardier;
import lotr.common.entity.npc.LOTREntityAvariElf;
import lotr.common.entity.npc.LOTREntityAvariElfBannerBearer;
import lotr.common.entity.npc.LOTREntityAvariElfScout;
import lotr.common.entity.npc.LOTREntityAvariElfWarrior;
import lotr.common.entity.npc.LOTREntityBarrowWight2;
import lotr.common.entity.npc.LOTREntityBlackUruk;
import lotr.common.entity.npc.LOTREntityBlackUrukArcher;
import lotr.common.entity.npc.LOTREntityBlackUrukBannerBearer;
import lotr.common.entity.npc.LOTREntityBlackUrukBerserk;
import lotr.common.entity.npc.LOTREntityBlacklock;
import lotr.common.entity.npc.LOTREntityBlacklockAxeThrower;
import lotr.common.entity.npc.LOTREntityBlacklockWarrior;
import lotr.common.entity.npc.LOTREntityBlacklockZnam;
import lotr.common.entity.npc.LOTREntityBlackrootArcher;
import lotr.common.entity.npc.LOTREntityBlackrootBannerBearer;
import lotr.common.entity.npc.LOTREntityBlackrootSoldier;
import lotr.common.entity.npc.LOTREntityBlueDwarf;
import lotr.common.entity.npc.LOTREntityBlueDwarfAxeThrower;
import lotr.common.entity.npc.LOTREntityBlueDwarfBannerBearer;
import lotr.common.entity.npc.LOTREntityBlueDwarfWarrior;
import lotr.common.entity.npc.LOTREntityBreeBannerBearer;
import lotr.common.entity.npc.LOTREntityBreeFarmhand;
import lotr.common.entity.npc.LOTREntityBreeGuard;
import lotr.common.entity.npc.LOTREntityBreeGuardCrossbow;
import lotr.common.entity.npc.LOTREntityCorsair;
import lotr.common.entity.npc.LOTREntityDaleArcher;
import lotr.common.entity.npc.LOTREntityDaleBannerBearer;
import lotr.common.entity.npc.LOTREntityDaleLevyman;
import lotr.common.entity.npc.LOTREntityDaleSoldier;
import lotr.common.entity.npc.LOTREntityDolAmrothArcher;
import lotr.common.entity.npc.LOTREntityDolAmrothBannerBearer;
import lotr.common.entity.npc.LOTREntityDolAmrothSoldier;
import lotr.common.entity.npc.LOTREntityDolGuldurBannerBearer;
import lotr.common.entity.npc.LOTREntityDolGuldurOrc;
import lotr.common.entity.npc.LOTREntityDolGuldurOrcArcher;
import lotr.common.entity.npc.LOTREntityDolGuldurUruk;
import lotr.common.entity.npc.LOTREntityDolGuldurUrukArcher;
import lotr.common.entity.npc.LOTREntityDolGuldurUrukBannerBearer;
import lotr.common.entity.npc.LOTREntityDolGuldurUrukBerserk;
import lotr.common.entity.npc.LOTREntityDorwinionBannerBearer;
import lotr.common.entity.npc.LOTREntityDorwinionCrossbower;
import lotr.common.entity.npc.LOTREntityDorwinionElfArcher;
import lotr.common.entity.npc.LOTREntityDorwinionElfBannerBearer;
import lotr.common.entity.npc.LOTREntityDorwinionElfWarrior;
import lotr.common.entity.npc.LOTREntityDorwinionGuard;
import lotr.common.entity.npc.LOTREntityDorwinionVinehand;
import lotr.common.entity.npc.LOTREntityDunlending;
import lotr.common.entity.npc.LOTREntityDunlendingArcher;
import lotr.common.entity.npc.LOTREntityDunlendingAxeThrower;
import lotr.common.entity.npc.LOTREntityDunlendingBannerBearer;
import lotr.common.entity.npc.LOTREntityDunlendingBerserker;
import lotr.common.entity.npc.LOTREntityDunlendingWarrior;
import lotr.common.entity.npc.LOTREntityDurmethBannerBearer;
import lotr.common.entity.npc.LOTREntityDurmethOrc;
import lotr.common.entity.npc.LOTREntityDurmethOrcArcher;
import lotr.common.entity.npc.LOTREntityDurmethOrcWarrior;
import lotr.common.entity.npc.LOTREntityDurmethOrcWarriorArcher;
import lotr.common.entity.npc.LOTREntityDurmethWarg;
import lotr.common.entity.npc.LOTREntityDurmethWarriorBannerBearer;
import lotr.common.entity.npc.LOTREntityDwarf;
import lotr.common.entity.npc.LOTREntityDwarfAxeThrower;
import lotr.common.entity.npc.LOTREntityDwarfBannerBearer;
import lotr.common.entity.npc.LOTREntityDwarfBerserk;
import lotr.common.entity.npc.LOTREntityDwarfWarrior;
import lotr.common.entity.npc.LOTREntityEasterlingArcher;
import lotr.common.entity.npc.LOTREntityEasterlingBannerBearer;
import lotr.common.entity.npc.LOTREntityEasterlingFarmhand;
import lotr.common.entity.npc.LOTREntityEasterlingFireThrower;
import lotr.common.entity.npc.LOTREntityEasterlingGoldWarrior;
import lotr.common.entity.npc.LOTREntityEasterlingLevyman;
import lotr.common.entity.npc.LOTREntityEasterlingWarrior;
import lotr.common.entity.npc.LOTREntityEreborDwarf;
import lotr.common.entity.npc.LOTREntityEreborDwarfAxeThrower;
import lotr.common.entity.npc.LOTREntityEreborDwarfBannerBearer;
import lotr.common.entity.npc.LOTREntityEreborDwarfBerserk;
import lotr.common.entity.npc.LOTREntityEreborDwarfCrossbow;
import lotr.common.entity.npc.LOTREntityEreborDwarfWarrior;
import lotr.common.entity.npc.LOTREntityEsgarothBannerBearer;
import lotr.common.entity.npc.LOTREntityGaladhrimBannerBearer;
import lotr.common.entity.npc.LOTREntityGaladhrimElf;
import lotr.common.entity.npc.LOTREntityGaladhrimWarden;
import lotr.common.entity.npc.LOTREntityGaladhrimWarrior;
import lotr.common.entity.npc.LOTREntityGondorArcher;
import lotr.common.entity.npc.LOTREntityGondorBannerBearer;
import lotr.common.entity.npc.LOTREntityGondorFarmhand;
import lotr.common.entity.npc.LOTREntityGondorLevyman;
import lotr.common.entity.npc.LOTREntityGondorSoldier;
import lotr.common.entity.npc.LOTREntityGondorTowerGuard;
import lotr.common.entity.npc.LOTREntityGulfHaradArcher;
import lotr.common.entity.npc.LOTREntityGulfHaradBannerBearer;
import lotr.common.entity.npc.LOTREntityGulfHaradWarrior;
import lotr.common.entity.npc.LOTREntityGundabadBannerBearer;
import lotr.common.entity.npc.LOTREntityGundabadCaveTroll;
import lotr.common.entity.npc.LOTREntityGundabadOrc;
import lotr.common.entity.npc.LOTREntityGundabadOrcArcher;
import lotr.common.entity.npc.LOTREntityGundabadUruk;
import lotr.common.entity.npc.LOTREntityGundabadUrukArcher;
import lotr.common.entity.npc.LOTREntityGundabadWarg;
import lotr.common.entity.npc.LOTREntityHalfTroll;
import lotr.common.entity.npc.LOTREntityHalfTrollBannerBearer;
import lotr.common.entity.npc.LOTREntityHalfTrollWarrior;
import lotr.common.entity.npc.LOTREntityHaradSlave;
import lotr.common.entity.npc.LOTREntityHarnedorArcher;
import lotr.common.entity.npc.LOTREntityHarnedorBannerBearer;
import lotr.common.entity.npc.LOTREntityHarnedorFarmhand;
import lotr.common.entity.npc.LOTREntityHarnedorWarrior;
import lotr.common.entity.npc.LOTREntityHighElf;
import lotr.common.entity.npc.LOTREntityHighElfBannerBearer;
import lotr.common.entity.npc.LOTREntityHighElfWarrior;
import lotr.common.entity.npc.LOTREntityHobbitBounder;
import lotr.common.entity.npc.LOTREntityHobbitBounder2;
import lotr.common.entity.npc.LOTREntityHobbitFarmhand;
import lotr.common.entity.npc.LOTREntityIronfist;
import lotr.common.entity.npc.LOTREntityIronfistBerserk;
import lotr.common.entity.npc.LOTREntityIronfistWarrior;
import lotr.common.entity.npc.LOTREntityIronfistZnam;
import lotr.common.entity.npc.LOTREntityIsengardSnaga;
import lotr.common.entity.npc.LOTREntityIsengardSnagaArcher;
import lotr.common.entity.npc.LOTREntityLamedonArcher;
import lotr.common.entity.npc.LOTREntityLamedonBannerBearer;
import lotr.common.entity.npc.LOTREntityLamedonHillman;
import lotr.common.entity.npc.LOTREntityLamedonSoldier;
import lotr.common.entity.npc.LOTREntityLebenninBannerBearer;
import lotr.common.entity.npc.LOTREntityLebenninLevyman;
import lotr.common.entity.npc.LOTREntityLossarnachAxeman;
import lotr.common.entity.npc.LOTREntityLossarnachBannerBearer;
import lotr.common.entity.npc.LOTREntityMinasMorgulBannerBearer;
import lotr.common.entity.npc.LOTREntityMirkTroll;
import lotr.common.entity.npc.LOTREntityMirkwoodSpider;
import lotr.common.entity.npc.LOTREntityMordorBannerBearer;
import lotr.common.entity.npc.LOTREntityMordorOrc;
import lotr.common.entity.npc.LOTREntityMordorOrcArcher;
import lotr.common.entity.npc.LOTREntityMordorOrcBombardier;
import lotr.common.entity.npc.LOTREntityMordorSpider;
import lotr.common.entity.npc.LOTREntityMordorWarg;
import lotr.common.entity.npc.LOTREntityMordorWargBombardier;
import lotr.common.entity.npc.LOTREntityMoredainBannerBearer;
import lotr.common.entity.npc.LOTREntityMoredainWarrior;
import lotr.common.entity.npc.LOTREntityMoriaOrc;
import lotr.common.entity.npc.LOTREntityMoriaOrcArcher;
import lotr.common.entity.npc.LOTREntityMountainTroll;
import lotr.common.entity.npc.LOTREntityNanUngolBannerBearer;
import lotr.common.entity.npc.LOTREntityNearHaradBannerBearer;
import lotr.common.entity.npc.LOTREntityNearHaradrimArcher;
import lotr.common.entity.npc.LOTREntityNearHaradrimWarrior;
import lotr.common.entity.npc.LOTREntityNomadArcher;
import lotr.common.entity.npc.LOTREntityNomadBannerBearer;
import lotr.common.entity.npc.LOTREntityNomadWarrior;
import lotr.common.entity.npc.LOTREntityNurnSlave;
import lotr.common.entity.npc.LOTREntityOlogHai;
import lotr.common.entity.npc.LOTREntityPelargirBannerBearer;
import lotr.common.entity.npc.LOTREntityPelargirMarine;
import lotr.common.entity.npc.LOTREntityPinnathGelinBannerBearer;
import lotr.common.entity.npc.LOTREntityPinnathGelinSoldier;
import lotr.common.entity.npc.LOTREntityRangerIthilien;
import lotr.common.entity.npc.LOTREntityRangerIthilienBannerBearer;
import lotr.common.entity.npc.LOTREntityRangerNorth;
import lotr.common.entity.npc.LOTREntityRangerNorthBannerBearer;
import lotr.common.entity.npc.LOTREntityRivendellBannerBearer;
import lotr.common.entity.npc.LOTREntityRivendellElf;
import lotr.common.entity.npc.LOTREntityRivendellWarrior;
import lotr.common.entity.npc.LOTREntityRohanBannerBearer;
import lotr.common.entity.npc.LOTREntityRohanFarmhand;
import lotr.common.entity.npc.LOTREntityRohirrimArcher;
import lotr.common.entity.npc.LOTREntityRohirrimWarrior;
import lotr.common.entity.npc.LOTREntitySouthronChampion;
import lotr.common.entity.npc.LOTREntityStiffbeard;
import lotr.common.entity.npc.LOTREntityStiffbeardCrossbow;
import lotr.common.entity.npc.LOTREntityStiffbeardWarrior;
import lotr.common.entity.npc.LOTREntityStiffbeardZnam;
import lotr.common.entity.npc.LOTREntityStonefoot;
import lotr.common.entity.npc.LOTREntityStonefootFlameThrower;
import lotr.common.entity.npc.LOTREntityStonefootWarrior;
import lotr.common.entity.npc.LOTREntityStonefootZnam;
import lotr.common.entity.npc.LOTREntitySwanKnight;
import lotr.common.entity.npc.LOTREntityTauredainBannerBearer;
import lotr.common.entity.npc.LOTREntityTauredainBlowgunner;
import lotr.common.entity.npc.LOTREntityTauredainFarmhand;
import lotr.common.entity.npc.LOTREntityTauredainWarrior;
import lotr.common.entity.npc.LOTREntityTroll;
import lotr.common.entity.npc.LOTREntityTundraSnowTroll;
import lotr.common.entity.npc.LOTREntityUmbarArcher;
import lotr.common.entity.npc.LOTREntityUmbarBannerBearer;
import lotr.common.entity.npc.LOTREntityUmbarWarrior;
import lotr.common.entity.npc.LOTREntityUrukHai;
import lotr.common.entity.npc.LOTREntityUrukHaiBannerBearer;
import lotr.common.entity.npc.LOTREntityUrukHaiBerserker;
import lotr.common.entity.npc.LOTREntityUrukHaiBerserkerArcher;
import lotr.common.entity.npc.LOTREntityUrukHaiCrossbower;
import lotr.common.entity.npc.LOTREntityUrukHaiSapper;
import lotr.common.entity.npc.LOTREntityUrukWarg;
import lotr.common.entity.npc.LOTREntityUrukWargBombardier;
import lotr.common.entity.npc.LOTREntityUtumnoSnowTroll;
import lotr.common.entity.npc.LOTREntityWindDwarf;
import lotr.common.entity.npc.LOTREntityWindDwarfAxeThrower;
import lotr.common.entity.npc.LOTREntityWindDwarfBannerBearer;
import lotr.common.entity.npc.LOTREntityWindDwarfWarrior;
import lotr.common.entity.npc.LOTREntityWoodElf;
import lotr.common.entity.npc.LOTREntityWoodElfBannerBearer;
import lotr.common.entity.npc.LOTREntityWoodElfScout;
import lotr.common.entity.npc.LOTREntityWoodElfWarrior;
import lotr.common.entity.npc.LOTRHiredNPCInfo;
import lotr.common.entity.npc.LOTRUnitTradeEntry;
import net.minecraft.item.Item;

public class LOTRUnitTradeEntries {
    public static LOTRUnitTradeEntries MORDOR_ORC_MERCENARY_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityMordorOrc.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrcArcher.class, 40, 50.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrcBombardier.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityMordorWarg.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrc.class, LOTREntityMordorWarg.class, "MordorOrc_Warg", 40, 100.0f).setMountArmor(LOTRMod.wargArmorMordor, 0.5f), new LOTRUnitTradeEntry(LOTREntityMordorOrcArcher.class, LOTREntityMordorWarg.class, "MordorOrcArcher_Warg", 60, 150.0f).setMountArmor(LOTRMod.wargArmorMordor, 0.5f), new LOTRUnitTradeEntry(LOTREntityMordorWargBombardier.class, 2050, 2500.0f), new LOTRUnitTradeEntry(LOTREntityOlogHai.class, 520, 350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityMordorBannerBearer.class, 40, 150.0f), new LOTRUnitTradeEntry(LOTREntityMinasMorgulBannerBearer.class, 40, 150.0f));
    public static LOTRUnitTradeEntries GONDORIAN_CAPTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityGondorLevyman.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityGondorSoldier.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityGondorArcher.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityGondorSoldier.class, LOTREntityHorse.class, "GondorSoldier_Horse", 50, 150.0f).setMountArmor(LOTRMod.horseArmorGondor), new LOTRUnitTradeEntry(LOTREntityGondorTowerGuard.class, 50, 250.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityGondorBannerBearer.class, 50, 200.0f));
    public static LOTRUnitTradeEntries DWARF_COMMANDER = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityDwarf.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityDwarfWarrior.class, 30, 50.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityDwarfAxeThrower.class, 50, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityDwarfBerserk.class, 60, 150.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityDwarfWarrior.class, LOTREntityRam.class, "DwarfWarrior_Ram", 50, 150.0f).setMountArmor(LOTRMod.ramArmorDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityDwarfAxeThrower.class, LOTREntityRam.class, "DwarfAxeThrower_Ram", 70, 200.0f).setMountArmor(LOTRMod.ramArmorDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityDwarfBannerBearer.class, 50, 200.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF));
    public static LOTRUnitTradeEntries URUK_HAI_MERCENARY_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityIsengardSnaga.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityIsengardSnagaArcher.class, 40, 50.0f), new LOTRUnitTradeEntry(LOTREntityUrukHai.class, 40, 0.0f), new LOTRUnitTradeEntry(LOTREntityUrukHaiCrossbower.class, 60, 50.0f), new LOTRUnitTradeEntry(LOTREntityUrukHaiSapper.class, 70, 100.0f), new LOTRUnitTradeEntry(LOTREntityUrukHaiBerserker.class, 60, 150.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityUrukHaiBerserkerArcher.class, 80, 200.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityUrukWarg.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityIsengardSnaga.class, LOTREntityUrukWarg.class, "IsengardSnaga_Warg", 40, 100.0f).setMountArmor(LOTRMod.wargArmorUruk, 0.5f), new LOTRUnitTradeEntry(LOTREntityIsengardSnagaArcher.class, LOTREntityUrukWarg.class, "IsengardSnagaArcher_Warg", 60, 150.0f).setMountArmor(LOTRMod.wargArmorUruk, 0.5f), new LOTRUnitTradeEntry(LOTREntityUrukWargBombardier.class, 2050, 2500.0f), new LOTRUnitTradeEntry(LOTREntityUrukHaiBannerBearer.class, 60, 150.0f));
    public static LOTRUnitTradeEntries ELF_LORD = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityGaladhrimElf.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityGaladhrimWarden.class, 40, 50.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityGaladhrimWarrior.class, 50, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityGaladhrimWarrior.class, LOTREntityHorse.class, "GaladhrimWarrior_Horse", 70, 200.0f).setMountArmor(LOTRMod.horseArmorGaladhrim).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityGaladhrimBannerBearer.class, 70, 250.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF));
    public static LOTRUnitTradeEntries ROHIRRIM_MARSHAL = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityRohirrimWarrior.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityRohirrimArcher.class, 50, 50.0f), new LOTRUnitTradeEntry(LOTREntityRohirrimWarrior.class, LOTREntityHorse.class, "Rohirrim_Horse", 50, 100.0f).setMountArmor(LOTRMod.horseArmorRohan), new LOTRUnitTradeEntry(LOTREntityRohirrimArcher.class, LOTREntityHorse.class, "RohirrimArcher_Horse", 70, 150.0f).setMountArmor(LOTRMod.horseArmorRohan), new LOTRUnitTradeEntry(LOTREntityRohanBannerBearer.class, 50, 150.0f));
    public static LOTRUnitTradeEntries HOBBIT_SHIRRIFF = new LOTRUnitTradeEntries(50.0f, new LOTRUnitTradeEntry(LOTREntityHobbitBounder.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityHobbitBounder2.class, 30, 30.0f), new LOTRUnitTradeEntry(LOTREntityHobbitBounder.class, LOTREntityShirePony.class, "HobbitBounder_Pony", 40, 50.0f));
    public static LOTRUnitTradeEntries DUNLENDING_WARLORD = new LOTRUnitTradeEntries(100.0f, new LOTRUnitTradeEntry(LOTREntityDunlending.class, 15, 0.0f), new LOTRUnitTradeEntry(LOTREntityDunlendingWarrior.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityDunlendingArcher.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityDunlendingAxeThrower.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityDunlendingBerserker.class, 50, 200.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityDunlendingBannerBearer.class, 50, 200.0f));
    public static LOTRUnitTradeEntries WOOD_ELF_CAPTAIN = new LOTRUnitTradeEntries(250.0f, new LOTRUnitTradeEntry(LOTREntityWoodElf.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityWoodElfScout.class, 40, 50.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityWoodElfWarrior.class, 50, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityWoodElfWarrior.class, LOTREntityElk.class, "WoodElfWarrior_Elk", 70, 200.0f).setMountArmor(LOTRMod.elkArmorWoodElven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityWoodElfBannerBearer.class, 70, 250.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF));
    public static LOTRUnitTradeEntries ANGMAR_ORC_MERCENARY_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityAngmarOrc.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityAngmarOrcArcher.class, 40, 50.0f), new LOTRUnitTradeEntry(LOTREntityAngmarOrcBombardier.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityAngmarWarg.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityAngmarOrc.class, LOTREntityAngmarWarg.class, "AngmarOrc_Warg", 40, 100.0f).setMountArmor(LOTRMod.wargArmorAngmar, 0.5f), new LOTRUnitTradeEntry(LOTREntityAngmarOrcArcher.class, LOTREntityAngmarWarg.class, "AngmarOrcArcher_Warg", 60, 150.0f).setMountArmor(LOTRMod.wargArmorAngmar, 0.5f), new LOTRUnitTradeEntry(LOTREntityAngmarWargBombardier.class, 2050, 2500.0f), new LOTRUnitTradeEntry(LOTREntityTroll.class, 100, 250.0f), new LOTRUnitTradeEntry(LOTREntityMountainTroll.class, 120, 350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngmarBannerBearer.class, 40, 150.0f));
    public static LOTRUnitTradeEntries MORDOR_ORC_SLAVER = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityNurnSlave.class, 40, 0.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
    public static LOTRUnitTradeEntries MORDOR_ORC_SPIDER_KEEPER = new LOTRUnitTradeEntries(250.0f, new LOTRUnitTradeEntry(LOTREntityMordorSpider.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrc.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrcArcher.class, 40, 0.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrc.class, LOTREntityMordorSpider.class, "MordorOrc_Spider", 50, 50.0f), new LOTRUnitTradeEntry(LOTREntityMordorOrcArcher.class, LOTREntityMordorSpider.class, "MordorOrcArcher_Spider", 70, 100.0f), new LOTRUnitTradeEntry(LOTREntityNanUngolBannerBearer.class, 40, 150.0f));
    public static LOTRUnitTradeEntries GUNDABAD_ORC_MERCENARY_CAPTAIN = new LOTRUnitTradeEntries(100.0f, new LOTRUnitTradeEntry(LOTREntityGundabadOrc.class, 15, 0.0f), new LOTRUnitTradeEntry(LOTREntityGundabadOrcArcher.class, 35, 50.0f), new LOTRUnitTradeEntry(LOTREntityGundabadWarg.class, 20, 50.0f), new LOTRUnitTradeEntry(LOTREntityGundabadOrc.class, LOTREntityGundabadWarg.class, "GundabadOrc_Warg", 35, 100.0f), new LOTRUnitTradeEntry(LOTREntityGundabadOrcArcher.class, LOTREntityGundabadWarg.class, "GundabadOrcArcher_Warg", 55, 150.0f), new LOTRUnitTradeEntry(LOTREntityGundabadUruk.class, 40, 250.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityGundabadUrukArcher.class, 60, 300.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityGundabadBannerBearer.class, 35, 150.0f));
    public static LOTRUnitTradeEntries RANGER_NORTH_CAPTAIN = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityRangerNorth.class, 50, 0.0f), new LOTRUnitTradeEntry(LOTREntityRangerNorth.class, LOTREntityHorse.class, "RangerNorth_Horse", 70, 100.0f), new LOTRUnitTradeEntry(LOTREntityRangerNorthBannerBearer.class, 70, 150.0f));
    public static LOTRUnitTradeEntries HOBBIT_FARMER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityHobbitFarmhand.class, 40, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
    public static LOTRUnitTradeEntries HIGH_ELF_LORD = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityHighElf.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityHighElfWarrior.class, 50, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityHighElfWarrior.class, LOTREntityHorse.class, "HighElfWarrior_Horse", 70, 200.0f).setMountArmor(LOTRMod.horseArmorHighElven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityHighElfBannerBearer.class, 70, 250.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF));
    public static LOTRUnitTradeEntries NEAR_HARADRIM_WARLORD = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityNearHaradrimWarrior.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityNearHaradrimArcher.class, 50, 50.0f), new LOTRUnitTradeEntry(LOTREntitySouthronChampion.class, LOTREntityHorse.class, "SouthronChampion_Horse", 60, 100.0f).setMountArmor(LOTRMod.horseArmorNearHarad).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityNearHaradBannerBearer.class, 50, 150.0f));
    public static LOTRUnitTradeEntries BLUE_DWARF_COMMANDER = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityBlueDwarf.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityBlueDwarfWarrior.class, 30, 50.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityBlueDwarfAxeThrower.class, 50, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityBlueDwarfWarrior.class, LOTREntityWildBoar.class, "BlueDwarfWarrior_Boar", 50, 150.0f).setMountArmor(LOTRMod.boarArmorBlueDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityBlueDwarfAxeThrower.class, LOTREntityWildBoar.class, "BlueDwarfAxeThrower_Boar", 70, 200.0f).setMountArmor(LOTRMod.boarArmorBlueDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityBlueDwarfBannerBearer.class, 50, 200.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF));
    public static LOTRUnitTradeEntries DOL_GULDUR_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityDolGuldurOrc.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityDolGuldurOrcArcher.class, 40, 50.0f), new LOTRUnitTradeEntry(LOTREntityDolGuldurUruk.class, 45, 350.0f), new LOTRUnitTradeEntry(LOTREntityDolGuldurUrukArcher.class, 50, 350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityDolGuldurUrukBerserk.class, 60, 450.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityMirkwoodSpider.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityDolGuldurOrc.class, LOTREntityMirkwoodSpider.class, "DolGuldurOrc_Spider", 40, 100.0f), new LOTRUnitTradeEntry(LOTREntityDolGuldurOrcArcher.class, LOTREntityMirkwoodSpider.class, "DolGuldurOrcArcher_Spider", 60, 150.0f), new LOTRUnitTradeEntry(LOTREntityMirkTroll.class, 100, 350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityDolGuldurUrukBannerBearer.class, 60, 0.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityDolGuldurBannerBearer.class, 40, 0.0f));
    public static LOTRUnitTradeEntries RANGER_ITHILIEN_CAPTAIN = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityRangerIthilien.class, 50, 0.0f), new LOTRUnitTradeEntry(LOTREntityRangerIthilienBannerBearer.class, 70, 150.0f));
    public static LOTRUnitTradeEntries HALF_TROLL_WARLORD = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityHalfTroll.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityHalfTrollWarrior.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityHalfTrollWarrior.class, LOTREntityRhino.class, "HalfTrollWarrior_Rhino", 70, 200.0f).setMountArmor(LOTRMod.rhinoArmorHalfTroll, 0.5f), new LOTRUnitTradeEntry(LOTREntityHalfTrollBannerBearer.class, 70, 150.0f));
    public static LOTRUnitTradeEntries DOL_AMROTH_CAPTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityDolAmrothSoldier.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityDolAmrothArcher.class, 50, 50.0f), new LOTRUnitTradeEntry(LOTREntitySwanKnight.class, 50, 100.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityDolAmrothSoldier.class, LOTREntityHorse.class, "DolAmrothSoldier_Horse", 50, 100.0f).setMountArmor(LOTRMod.horseArmorDolAmroth, 0.5f), new LOTRUnitTradeEntry(LOTREntitySwanKnight.class, LOTREntityHorse.class, "SwanKnight_Horse", 70, 200.0f).setMountArmor(LOTRMod.horseArmorDolAmroth).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityDolAmrothBannerBearer.class, 50, 150.0f));
    public static LOTRUnitTradeEntries MOREDAIN_CHIEFTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityMoredainWarrior.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityMoredainWarrior.class, LOTREntityZebra.class, "MoredainWarrior_Zebra", 40, 100.0f), new LOTRUnitTradeEntry(LOTREntityMoredainBannerBearer.class, 40, 150.0f));
    public static LOTRUnitTradeEntries ANGMAR_HILLMAN_CHIEFTAIN = new LOTRUnitTradeEntries(100.0f, new LOTRUnitTradeEntry(LOTREntityAngmarHillman.class, 15, 0.0f), new LOTRUnitTradeEntry(LOTREntityAngmarHillmanWarrior.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityAngmarHillmanAxeThrower.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityAngmarHillman.class, LOTREntityAngmarWarg.class, "AngmarHillman_Warg", 35, 100.0f), new LOTRUnitTradeEntry(LOTREntityAngmarHillmanWarrior.class, LOTREntityAngmarWarg.class, "AngmarHillmanWarrior_Warg", 50, 150.0f).setMountArmor(LOTRMod.wargArmorAngmar, 0.3f), new LOTRUnitTradeEntry(LOTREntityAngmarHillmanAxeThrower.class, LOTREntityAngmarWarg.class, "AngmarHillmanAxeThrower_Warg", 70, 200.0f).setMountArmor(LOTRMod.wargArmorAngmar, 0.3f), new LOTRUnitTradeEntry(LOTREntityAngmarHillmanBannerBearer.class, 50, 200.0f));
    public static LOTRUnitTradeEntries TAUREDAIN_CHIEFTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityTauredainWarrior.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityTauredainBlowgunner.class, 50, 50.0f), new LOTRUnitTradeEntry(LOTREntityTauredainBannerBearer.class, 50, 150.0f));
    public static LOTRUnitTradeEntries TAUREDAIN_FARMER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityTauredainFarmhand.class, 40, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
    public static LOTRUnitTradeEntries DALE_CAPTAIN = new LOTRUnitTradeEntries(100.0f, new LOTRUnitTradeEntry(LOTREntityDaleLevyman.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityDaleSoldier.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityDaleArcher.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityDaleSoldier.class, LOTREntityHorse.class, "DaleSoldier_Horse", 50, 150.0f).setMountArmor(LOTRMod.horseArmorDale), new LOTRUnitTradeEntry(LOTREntityDaleBannerBearer.class, 50, 200.0f), new LOTRUnitTradeEntry(LOTREntityEsgarothBannerBearer.class, 50, 200.0f));
    public static LOTRUnitTradeEntries DORWINION_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityDorwinionGuard.class, 40, 0.0f), new LOTRUnitTradeEntry(LOTREntityDorwinionCrossbower.class, 60, 50.0f), new LOTRUnitTradeEntry(LOTREntityDorwinionBannerBearer.class, 60, 150.0f));
    public static LOTRUnitTradeEntries DORWINION_ELF_CAPTAIN = new LOTRUnitTradeEntries(250.0f, new LOTRUnitTradeEntry(LOTREntityDorwinionElfWarrior.class, 50, 0.0f), new LOTRUnitTradeEntry(LOTREntityDorwinionElfArcher.class, 70, 50.0f), new LOTRUnitTradeEntry(LOTREntityDorwinionElfBannerBearer.class, 70, 150.0f));
    public static LOTRUnitTradeEntries DORWINION_VINEKEEPER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityDorwinionVinehand.class, 40, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
    public static LOTRUnitTradeEntries LOSSARNACH_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityGondorLevyman.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityLossarnachAxeman.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityLossarnachBannerBearer.class, 50, 200.0f));
    public static LOTRUnitTradeEntries PELARGIR_CAPTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityLebenninLevyman.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityPelargirMarine.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityPelargirBannerBearer.class, 50, 200.0f));
    public static LOTRUnitTradeEntries PINNATH_GELIN_CAPTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityGondorLevyman.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityPinnathGelinSoldier.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityPinnathGelinSoldier.class, LOTREntityHorse.class, "PinnathGelinSoldier_Horse", 50, 150.0f).setMountArmor(LOTRMod.horseArmorGondor), new LOTRUnitTradeEntry(LOTREntityPinnathGelinBannerBearer.class, 50, 200.0f));
    public static LOTRUnitTradeEntries BLACKROOT_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityGondorLevyman.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityBlackrootSoldier.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityBlackrootArcher.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityBlackrootSoldier.class, LOTREntityHorse.class, "BlackrootSoldier_Horse", 50, 150.0f).setMountArmor(LOTRMod.horseArmorGondor), new LOTRUnitTradeEntry(LOTREntityBlackrootBannerBearer.class, 50, 200.0f));
    public static LOTRUnitTradeEntries GONDOR_FARMER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityGondorFarmhand.class, 40, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
    public static LOTRUnitTradeEntries LEBENNIN_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityLebenninLevyman.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityGondorSoldier.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityGondorArcher.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityLebenninBannerBearer.class, 40, 150.0f));
    public static LOTRUnitTradeEntries LAMEDON_CAPTAIN = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityLamedonHillman.class, 15, 0.0f), new LOTRUnitTradeEntry(LOTREntityLamedonSoldier.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityLamedonArcher.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityLamedonSoldier.class, LOTREntityHorse.class, "LamedonSoldier_Horse", 50, 150.0f).setMountArmor(LOTRMod.horseArmorLamedon), new LOTRUnitTradeEntry(LOTREntityLamedonBannerBearer.class, 50, 200.0f));
    public static LOTRUnitTradeEntries ROHAN_FARMER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityRohanFarmhand.class, 40, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
    public static LOTRUnitTradeEntries EASTERLING_WARLORD = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityEasterlingLevyman.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityEasterlingWarrior.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityEasterlingArcher.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityEasterlingGoldWarrior.class, 50, 200.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityEasterlingWarrior.class, LOTREntityHorse.class, "EasterlingWarrior_Horse", 50, 150.0f), new LOTRUnitTradeEntry(LOTREntityEasterlingArcher.class, LOTREntityHorse.class, "EasterlingArcher_Horse", 70, 200.0f), new LOTRUnitTradeEntry(LOTREntityEasterlingGoldWarrior.class, LOTREntityHorse.class, "EasterlingGoldWarrior_Horse", 70, 300.0f).setMountArmor(LOTRMod.horseArmorRhunGold).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityEasterlingFireThrower.class, 60, 150.0f), new LOTRUnitTradeEntry(LOTREntityEasterlingBannerBearer.class, 50, 200.0f));
    public static LOTRUnitTradeEntries EASTERLING_FARMER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityEasterlingFarmhand.class, 40, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
    public static LOTRUnitTradeEntries RIVENDELL_LORD = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityRivendellElf.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityRivendellWarrior.class, 50, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityRivendellWarrior.class, LOTREntityHorse.class, "RivendellWarrior_Horse", 70, 200.0f).setMountArmor(LOTRMod.horseArmorRivendell).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityRivendellBannerBearer.class, 70, 250.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF));
    public static LOTRUnitTradeEntries HARNEDOR_WARLORD = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityHarnedorWarrior.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityHarnedorArcher.class, 40, 50.0f), new LOTRUnitTradeEntry(LOTREntityHarnedorWarrior.class, LOTREntityHorse.class, "HarnedorWarrior_Horse", 40, 100.0f), new LOTRUnitTradeEntry(LOTREntityHarnedorArcher.class, LOTREntityHorse.class, "HarnedorArcher_Horse", 60, 150.0f), new LOTRUnitTradeEntry(LOTREntityHarnedorBannerBearer.class, 40, 150.0f));
    public static LOTRUnitTradeEntries UMBAR_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityUmbarWarrior.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityUmbarArcher.class, 50, 50.0f), new LOTRUnitTradeEntry(LOTREntityUmbarWarrior.class, LOTREntityHorse.class, "UmbarWarrior_Horse", 50, 100.0f).setMountArmor(LOTRMod.horseArmorUmbar), new LOTRUnitTradeEntry(LOTREntityUmbarBannerBearer.class, 50, 150.0f));
    public static LOTRUnitTradeEntries CORSAIR_CAPTAIN = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityCorsair.class, 20, 0.0f).setExtraInfo("Corsair"));
    public static LOTRUnitTradeEntries NOMAD_WARLORD = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityNomadWarrior.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityNomadArcher.class, 40, 50.0f), new LOTRUnitTradeEntry(LOTREntityNomadWarrior.class, LOTREntityCamel.class, "NomadWarrior_Camel", 40, 100.0f), new LOTRUnitTradeEntry(LOTREntityNomadArcher.class, LOTREntityCamel.class, "NomadArcher_Camel", 60, 150.0f), new LOTRUnitTradeEntry(LOTREntityNomadBannerBearer.class, 40, 150.0f));
    public static LOTRUnitTradeEntries GULF_WARLORD = new LOTRUnitTradeEntries(150.0f, new LOTRUnitTradeEntry(LOTREntityGulfHaradWarrior.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityGulfHaradArcher.class, 50, 50.0f), new LOTRUnitTradeEntry(LOTREntityGulfHaradWarrior.class, LOTREntityHorse.class, "GulfWarrior_Horse", 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityGulfHaradArcher.class, LOTREntityHorse.class, "GulfArcher_Horse", 70, 150.0f), new LOTRUnitTradeEntry(LOTREntityGulfHaradBannerBearer.class, 50, 150.0f));
    public static LOTRUnitTradeEntries CORSAIR_SLAVER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityHaradSlave.class, 40, 0.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
    public static LOTRUnitTradeEntries HARNEDOR_FARMER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityHarnedorFarmhand.class, 40, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
    public static LOTRUnitTradeEntries BLACK_URUK_CAPTAIN = new LOTRUnitTradeEntries(400.0f, new LOTRUnitTradeEntry(LOTREntityBlackUruk.class, 60, 250.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityBlackUrukArcher.class, 80, 300.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityBlackUrukBerserk.class, 85, 350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityOlogHai.class, 120, 550.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityBlackUrukBannerBearer.class, 80, 400.0f).setPledgeExclusive());
    public static LOTRUnitTradeEntries RED_BLACKLOCK = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityBlacklock.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityBlacklockWarrior.class, 50, 50.0f), new LOTRUnitTradeEntry(LOTREntityBlacklockAxeThrower.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityBlacklockAxeThrower.class, LOTREntityWildBoar.class, "DwarfAxeThrower_Boar", 70, 150.0f).setMountArmor(LOTRMod.boarArmorRed).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityBlacklockWarrior.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 70, 150.0f).setMountArmor(LOTRMod.boarArmorRed).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityBlacklockZnam.class, 80, 600.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityBlacklockZnam.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 100, 650.0f).setMountArmor(LOTRMod.boarArmorRedGilded).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF));
    public static LOTRUnitTradeEntries RED_STONEFOOT = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityStonefoot.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityStonefootWarrior.class, 50, 50.0f), new LOTRUnitTradeEntry(LOTREntityStonefootWarrior.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 70, 150.0f).setMountArmor(LOTRMod.boarArmorRed).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityStonefootFlameThrower.class, 75, 500.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityStonefootFlameThrower.class, LOTREntityWildBoar.class, "DwarfFlame_Boar", 95, 550.0f).setMountArmor(LOTRMod.boarArmorRedGilded).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityStonefootZnam.class, 80, 600.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF));
    public static LOTRUnitTradeEntries RED_STIFFBEARD = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityStiffbeard.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityStiffbeardWarrior.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityStiffbeardCrossbow.class, 50, 100.0f), new LOTRUnitTradeEntry(LOTREntityStiffbeardWarrior.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 70, 150.0f).setMountArmor(LOTRMod.boarArmorRed).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityStiffbeardCrossbow.class, LOTREntityWildBoar.class, "DwarfAxeThrower_Boar", 70, 200.0f).setMountArmor(LOTRMod.boarArmorRedGilded).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityStiffbeardZnam.class, 80, 600.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityStiffbeardZnam.class, LOTREntityRam.class, "DwarfWarrior_Ram", 100, 650.0f).setMountArmor(LOTRMod.ramArmorRedDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF));
    public static LOTRUnitTradeEntries RED_IRONFIST = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityIronfist.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityIronfistWarrior.class, 30, 50.0f), new LOTRUnitTradeEntry(LOTREntityIronfistBerserk.class, 65, 200.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityIronfistBerserk.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 75, 250.0f).setMountArmor(LOTRMod.boarArmorRed).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityIronfistWarrior.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 70, 150.0f).setMountArmor(LOTRMod.boarArmorRed).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityIronfistZnam.class, 80, 600.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityIronfistZnam.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 100, 650.0f).setMountArmor(LOTRMod.boarArmorRedGilded).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF));
    public static LOTRUnitTradeEntries EREBOR_COMMANDER = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityEreborDwarf.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityEreborDwarfWarrior.class, 30, 50.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityEreborDwarfAxeThrower.class, 50, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityEreborDwarfBerserk.class, 60, 150.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityEreborDwarfCrossbow.class, 65, 180.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityEreborDwarfWarrior.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 50, 200.0f).setMountArmor(LOTRMod.boarArmorDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityEreborDwarfAxeThrower.class, LOTREntityWildBoar.class, "DwarfAxeThrower_Boar", 70, 200.0f).setMountArmor(LOTRMod.boarArmorDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityEreborDwarfCrossbow.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 75, 300.0f).setMountArmor(LOTRMod.boarArmorDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityEreborDwarfBerserk.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 75, 350.0f).setMountArmor(LOTRMod.boarArmorDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityEreborDwarfBannerBearer.class, 50, 200.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityEreborDwarfBannerBearer.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 70, 450.0f).setMountArmor(LOTRMod.boarArmorDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF));
    public static LOTRUnitTradeEntries WIND_COMMANDER = new LOTRUnitTradeEntries(200.0f, new LOTRUnitTradeEntry(LOTREntityWindDwarf.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityWindDwarfWarrior.class, 30, 50.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityWindDwarfAxeThrower.class, 50, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityWindDwarfWarrior.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 50, 200.0f).setMountArmor(LOTRMod.boarArmorDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityWindDwarfAxeThrower.class, LOTREntityWildBoar.class, "DwarfAxeThrower_Boar", 70, 200.0f).setMountArmor(LOTRMod.boarArmorDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityWindDwarfBannerBearer.class, 50, 200.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF), new LOTRUnitTradeEntry(LOTREntityWindDwarfBannerBearer.class, LOTREntityWildBoar.class, "DwarfWarrior_Boar", 70, 450.0f).setMountArmor(LOTRMod.boarArmorDwarven).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_DWARF));
    public static LOTRUnitTradeEntries ANGBAND = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityAngbandRuinsWraith.class, 43, 320.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandUruc.class, 50, 450.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandCrossbow.class, 55, 550.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandBerserk.class, 65, 650.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandZnam1.class, 65, 850.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityBarrowWight2.class, 85, 1150.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityUtumnoSnowTroll.class, 98, 1350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandTrollObsidian.class, 140, 1650.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandTrollFire.class, 160, 1850.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandBalrog.class, 7000, 10000.0f).setPledgeExclusive());
    public static LOTRUnitTradeEntries ANGBAND1 = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityAngbandSpiderIce.class, 95, 1350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandSpiderObsidian.class, 105, 1450.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandSpiderFire.class, 125, 1500.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandOrc.class, LOTREntityAngbandSpiderIce.class, "MordorOrc_Spider", 120, 1550.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandOrcArcher.class, LOTREntityAngbandSpiderObsidian.class, "MordorOrcArcher_Spider", 145, 1650.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandOrc.class, LOTREntityAngbandSpiderFire.class, "MordorOrc_Spider", 165, 1700.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandZnam.class, LOTREntityAngbandSpiderFire.class, "AngbandOrc_Warg", 99, 1850.0f).setPledgeExclusive());
    public static LOTRUnitTradeEntries ANGBAND3 = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityAngbandOrc.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityAngbandOrcArcher.class, 40, 300.0f), new LOTRUnitTradeEntry(LOTREntityAngbandElf.class, 45, 350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandOrcZnam.class, 65, 850.0f).setPledgeExclusive());
    public static LOTRUnitTradeEntries ANGBAND2 = new LOTRUnitTradeEntries(300.0f, new LOTRUnitTradeEntry(LOTREntityAngbandWarg.class, 25, 250.0f), new LOTRUnitTradeEntry(LOTREntityAngbandWargIce.class, 55, 650.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandWargObsidian.class, 65, 750.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandWargFire.class, 85, 800.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandOrc.class, LOTREntityAngbandWarg.class, "MordorOrc_Warg", 87, 850.0f).setMountArmor(LOTRMod.wargArmorAngband, 0.5f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandOrcArcher.class, LOTREntityAngbandWarg.class, "AngbandOrc_Warg", 95, 950.0f).setMountArmor(LOTRMod.wargArmorAngband, 0.5f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandUruc.class, LOTREntityAngbandWargIce.class, "AngbandUruc_Warg", 99, 1050.0f).setMountArmor(LOTRMod.wargArmorAngband, 0.5f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandUruc.class, LOTREntityAngbandWargObsidian.class, "AngbandUruc_Warg", 92, 1150.0f).setMountArmor(LOTRMod.wargArmorAngband, 0.5f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandUruc.class, LOTREntityAngbandWargFire.class, "AngbandUruc_Warg", 108, 1250.0f).setMountArmor(LOTRMod.wargArmorAngband, 0.5f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandCrossbow.class, LOTREntityAngbandWargIce.class, "AngbandUruc_Warg", 100, 950.0f).setMountArmor(LOTRMod.wargArmorAngband, 0.5f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandCrossbow.class, LOTREntityAngbandWargObsidian.class, "AngbandUruc_Warg", 102, 1150.0f).setMountArmor(LOTRMod.wargArmorAngband, 0.5f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandCrossbow.class, LOTREntityAngbandWargFire.class, "AngbandUruc_Warg", 118, 1250.0f).setMountArmor(LOTRMod.wargArmorAngband, 0.5f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandWargBombardier.class, 85, 1250.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityAngbandZnam2.class, LOTREntityAngbandWargFire.class, "AngbandOrc_Warg", 99, 1850.0f).setMountArmor(LOTRMod.wargArmorAngband, 0.5f).setPledgeExclusive());
    public static LOTRUnitTradeEntries DURMETH_ORC_MERCENARY_CAPTAIN = new LOTRUnitTradeEntries(100.0f, new LOTRUnitTradeEntry(LOTREntityDurmethOrc.class, 15, 0.0f), new LOTRUnitTradeEntry(LOTREntityDurmethOrcArcher.class, 35, 50.0f), new LOTRUnitTradeEntry(LOTREntityDurmethBannerBearer.class, 35, 150.0f), new LOTRUnitTradeEntry(LOTREntityDurmethOrcWarrior.class, 45, 100.0f), new LOTRUnitTradeEntry(LOTREntityDurmethOrcWarriorArcher.class, 55, 120.0f), new LOTRUnitTradeEntry(LOTREntityDurmethWarg.class, 20, 50.0f), new LOTRUnitTradeEntry(LOTREntityDurmethOrc.class, LOTREntityDurmethWarg.class, "GundabadOrc_Warg", 35, 100.0f), new LOTRUnitTradeEntry(LOTREntityDurmethOrcArcher.class, LOTREntityDurmethWarg.class, "GundabadOrcArcher_Warg", 55, 150.0f), new LOTRUnitTradeEntry(LOTREntityDurmethOrcWarrior.class, LOTREntityDurmethWarg.class, "GundabadOrc_Warg", 65, 100.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityDurmethOrcWarriorArcher.class, LOTREntityDurmethWarg.class, "GundabadOrcArcher_Warg", 75, 100.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityDurmethWarriorBannerBearer.class, LOTREntityDurmethWarg.class, "GundabadOrc_Warg", 85, 150.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityGundabadCaveTroll.class, 98, 350.0f).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityTundraSnowTroll.class, 108, 450.0f).setPledgeExclusive());
    public static LOTRUnitTradeEntries MORIA_ORC_MERCENARY_CAPTAIN = new LOTRUnitTradeEntries(100.0f, new LOTRUnitTradeEntry(LOTREntityMoriaOrc.class, 15, 0.0f), new LOTRUnitTradeEntry(LOTREntityMoriaOrcArcher.class, 35, 50.0f), new LOTRUnitTradeEntry(LOTREntityGundabadWarg.class, 20, 50.0f), new LOTRUnitTradeEntry(LOTREntityDurmethOrc.class, LOTREntityDurmethWarg.class, "GundabadOrc_Warg", 35, 100.0f), new LOTRUnitTradeEntry(LOTREntityMoriaOrcArcher.class, LOTREntityGundabadWarg.class, "GundabadOrcArcher_Warg", 55, 150.0f), new LOTRUnitTradeEntry(LOTREntityGundabadCaveTroll.class, 98, 350.0f).setPledgeExclusive());
    public static LOTRUnitTradeEntries AVARI_ELF_CAPTAIN = new LOTRUnitTradeEntries(250.0f, new LOTRUnitTradeEntry(LOTREntityAvariElf.class, 30, 0.0f), new LOTRUnitTradeEntry(LOTREntityAvariElfScout.class, 40, 50.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityAvariElfWarrior.class, 50, 100.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityAvariElfWarrior.class, LOTREntityHorse.class, "AvariElfWarrior_Elk", 70, 200.0f).setMountArmor(LOTRMod.horseArmorAvari).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF), new LOTRUnitTradeEntry(LOTREntityAvariElfBannerBearer.class, 70, 250.0f).setPledgeType(LOTRUnitTradeEntry.PledgeType.ANY_ELF));
    public static LOTRUnitTradeEntries BREE_CAPTAIN = new LOTRUnitTradeEntries(100.0f, new LOTRUnitTradeEntry(LOTREntityBreeGuard.class, 20, 0.0f), new LOTRUnitTradeEntry(LOTREntityBreeGuardCrossbow.class, 35, 0.0f), new LOTRUnitTradeEntry(LOTREntityBreeBannerBearer.class, 40, 150.0f), new LOTRUnitTradeEntry(LOTREntityBreeGuard.class, LOTREntityHorse.class, "BreeSoldier_Horse", 50, 350.0f).setMountArmor(LOTRMod.horseArmorIron).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityBreeGuardCrossbow.class, LOTREntityHorse.class, "BreeSoldier_Horse", 60, 450.0f).setMountArmor(LOTRMod.horseArmorIron).setPledgeExclusive(), new LOTRUnitTradeEntry(LOTREntityBreeBannerBearer.class, LOTREntityHorse.class, "BreeSoldier_Horse", 66, 550.0f).setMountArmor(LOTRMod.horseArmorIron).setPledgeExclusive());
    public static LOTRUnitTradeEntries BREE_FARMER = new LOTRUnitTradeEntries(0.0f, new LOTRUnitTradeEntry(LOTREntityBreeFarmhand.class, 40, 50.0f).setTask(LOTRHiredNPCInfo.Task.FARMER));
    public LOTRUnitTradeEntry[] tradeEntries;
    public static final int MOREDAIN_MERCENARY_COST = 20;

    public LOTRUnitTradeEntries(float baseAlignment, LOTRUnitTradeEntry ... trades) {
        this.tradeEntries = trades;
        for (LOTRUnitTradeEntry trade : trades) {
            trade.alignmentRequired += baseAlignment;
            if (trade.alignmentRequired >= 0.0f) continue;
            throw new IllegalArgumentException("Units cannot require negative alignment!");
        }
    }
}

